package com.goldthorp.ching.util;

public class Index {
  public static boolean[] getHexagram(int number) {
    boolean[] topTrigram = HEXAGRAMS[number - 1][0];
    boolean[] bottomTrigram = HEXAGRAMS[number - 1][1];
    return new boolean[]{
      bottomTrigram[0],
      bottomTrigram[1],
      bottomTrigram[2],
      topTrigram[0],
      topTrigram[1],
      topTrigram[2],
    };
  }

  final private static boolean[][][] HEXAGRAMS =  {
    {
      Trigrams.HEAVEN,
      Trigrams.HEAVEN
    },
    {
      Trigrams.EARTH,
      Trigrams.EARTH
    },
    {
      Trigrams.WATER,
      Trigrams.THUNDER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.WATER
    },
    {
      Trigrams.WATER,
      Trigrams.HEAVEN
    },
    {
      Trigrams.HEAVEN,
      Trigrams.WATER
    },
    {
      Trigrams.EARTH,
      Trigrams.WATER
    },
    {
      Trigrams.WATER,
      Trigrams.EARTH
    },
    {
      Trigrams.WIND,
      Trigrams.HEAVEN
    },
    {
      Trigrams.HEAVEN,
      Trigrams.LAKE
    },
    {
      Trigrams.EARTH,
      Trigrams.HEAVEN
    },
    {
      Trigrams.HEAVEN,
      Trigrams.EARTH
    },
    {
      Trigrams.HEAVEN,
      Trigrams.FIRE
    },
    {
      Trigrams.FIRE,
      Trigrams.HEAVEN
    },
    {
      Trigrams.EARTH,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.THUNDER,
      Trigrams.EARTH
    },
    {
      Trigrams.LAKE,
      Trigrams.THUNDER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.WIND
    },
    {
      Trigrams.EARTH,
      Trigrams.LAKE
    },
    {
      Trigrams.WIND,
      Trigrams.EARTH
    },
    {
      Trigrams.FIRE,
      Trigrams.THUNDER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.FIRE
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.EARTH
    },
    {
      Trigrams.EARTH,
      Trigrams.THUNDER
    },
    {
      Trigrams.HEAVEN,
      Trigrams.THUNDER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.HEAVEN
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.THUNDER
    },
    {
      Trigrams.LAKE,
      Trigrams.WIND
    },
    {
      Trigrams.WATER,
      Trigrams.WATER
    },
    {
      Trigrams.FIRE,
      Trigrams.FIRE
    },
    {
      Trigrams.LAKE,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.THUNDER,
      Trigrams.WIND
    },
    {
      Trigrams.HEAVEN,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.THUNDER,
      Trigrams.HEAVEN
    },
    {
      Trigrams.FIRE,
      Trigrams.EARTH
    },
    {
      Trigrams.EARTH,
      Trigrams.FIRE
    },
    {
      Trigrams.WIND,
      Trigrams.FIRE
    },
    {
      Trigrams.FIRE,
      Trigrams.LAKE
    },
    {
      Trigrams.WATER,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.THUNDER,
      Trigrams.WATER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.LAKE
    },
    {
      Trigrams.WIND,
      Trigrams.THUNDER
    },
    {
      Trigrams.LAKE,
      Trigrams.HEAVEN
    },
    {
      Trigrams.HEAVEN,
      Trigrams.WIND
    },
    {
      Trigrams.LAKE,
      Trigrams.EARTH
    },
    {
      Trigrams.EARTH,
      Trigrams.WIND
    },
    {
      Trigrams.LAKE,
      Trigrams.WATER
    },
    {
      Trigrams.WATER,
      Trigrams.WIND
    },
    {
      Trigrams.LAKE,
      Trigrams.FIRE
    },
    {
      Trigrams.FIRE,
      Trigrams.WIND
    },
    {
      Trigrams.THUNDER,
      Trigrams.THUNDER
    },
    {
      Trigrams.MOUNTAIN,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.WIND,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.THUNDER,
      Trigrams.LAKE
    },
    {
      Trigrams.THUNDER,
      Trigrams.FIRE
    },
    {
      Trigrams.FIRE,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.WIND,
      Trigrams.WIND
    },
    {
      Trigrams.LAKE,
      Trigrams.LAKE
    },
    {
      Trigrams.WIND,
      Trigrams.WATER
    },
    {
      Trigrams.WATER,
      Trigrams.LAKE
    },
    {
      Trigrams.WIND,
      Trigrams.LAKE
    },
    {
      Trigrams.THUNDER,
      Trigrams.MOUNTAIN
    },
    {
      Trigrams.WATER,
      Trigrams.FIRE
    },
    {
      Trigrams.FIRE,
      Trigrams.WATER
    },
  };

   private static class Trigrams {
    final static boolean[] HEAVEN = {true, true, true};
    final static boolean[] THUNDER = {true, false, false};
    final static boolean[] WATER = {false, true, false};
    final static boolean[] MOUNTAIN = {false, false, true};
    final static boolean[] EARTH = {false, false, false};
    final static boolean[] WIND = {false, true, true};
    final static boolean[] FIRE = {true, false, true};
    final static boolean[] LAKE = {true, true, false};
  }
}
